# Generated by Django 2.1.5 on 2020-07-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advisor_Name', models.CharField(max_length=30)),
                ('Advisor_Photo', models.CharField(max_length=50)),
            ],
        ),
    ]
